@hostname = http://localhost:3001


/// Users api ///
get {{hostname}}/users
###
/// sessions api ///
post {{hostname}}/users/signup
Content-Type:application/json

{
    "fullName":"Benjamin Mordedzi",
    "username":"benjamin100ist",
    "role":"national_admin",
    "email":"benjamin100ist@gmail.com",
    "password":"123456"
}